### ISSUE TITLE
More work needed on porting of the included views.

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/calendar#1]
There are nine predefined views in the Drupal module stored in a pair of data table. I have converted these to json files, one for each view, and included them in config. More work is needed because Views reports 'missing style plugin' at the moment.

**Comment by Graham-72** [comment]
Now partially solved, but under CONTEXTUAL FILTERS it is giving 'Broken/missing handler'.

**Comment by ghost** [comment]
> nine predefined views

I was going to ask "where do those views come from", as I could not find any evidence of these at drupal.org.

Looking through the source code, I found the `function calendar_views_templates()`, and I guess those views were created via `admin/structure/views/add-template`

Now, it seems like the whole "views templates" functionality has been dropped from backdrop (no, no smile).

Anyway, those views were, by definition,  created for the specific configuration of _this_ site at _this_ moment, so they are not good candidates for "default views" (which is what you are after).

So you should : 
1. Request backdrop core to back port `hook_views_templates()` process
2. Rework calendar's `calendar_views_template_construct()` to make it generate json data instead of php code

[One hour later : came across https://www.drupal.org/node/2492011 — good luck !]

**Comment by Graham-72** [comment]
@gifad Thanks for looking into this and for your comments. I met my immediate need by embedding a Google calendar into the site and the Drupal issue you quote makes me realise that it might take a great deal of effort to complete the port of this Calendar module. In fact, if ever I have the time I think I would prefer to start from scratch.

**Comment by herbdool** [comment]
I don't see hook_views_templates in Drupal either: https://api.drupal.org/api/views/views.api.php/group/views_hooks/7.x-3.x

**Comment by docwilmot** [comment]
@Graham-72 I dont know much about Calendar, but looking at the code, it seems the Calendar Views are meant to be generated on demand, based on the available fields and entity types in your site, and not as default views. I'd suggest the following way forward:
- add a form for generating new default views to the settings page.
- use the code from `calendar_views_templates()` to build the form.
- on submit use the code from `calendar_views_template_construct()` to build the default Views array.
- then borrow code from my [Default Views Convert to Config](https://github.com/backdrop-contrib/default_views_config) module to generate the config files.

**Comment by SamStamport** [comment]
I guess this is a dumb question ... Please tell me more about calendar_views_templates(). I searched the web for it, but got no relevant hits. I'm trying to figure out what to do next to finish the port of Calendar.

**Comment by docwilmot** [comment]
@SamStamport `hook_views_templates()` doesnt exist anymore, so you will need to accomplish its functionality by doing what I suggested one post ago.

**Comment by SamStamport** [comment]
OK. I guess I'm dumb ... Where do I find the code for calendar_views_templates() to create a form for generating new default views on the settings page?

**Comment by Graham-72** [comment]
@SamStamport rather than comment out line 217 in calendar_plugin_style.inc `module_load_include('inc', 'date_api', 'date_api_sql');` I think it should be replaced with `module_load_include('inc', 'date', 'views/date_sql_handler');`

I'm looking through some previous work of mine and will come back with anything else I find.

**Comment by Graham-72** [comment]
>Where do I find the code for calendar_views_templates()

It is in Calendar /includes, within calendar.views_template.inc

**Comment by Graham-72** [comment]
@SamStamport I have begun work on @docwilmot 's suggestion above.

**Comment by Graham-72** [comment]
I now think it best that there should be one default view configuration, giving page views for day, week, month and year, accessible from each other by tags, and from a menu item 'calendar' in the main menu.

**Comment by herbdool** [comment]
Closing now that there are some sample views. And template was removed since Backdrop doesn't have a way to create views from templates.
