### ISSUE TITLE
Contextual filter has 'Broken/missing handler'

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/calendar#2]
This is likely because `date_views_handler_is_date` function doesn't exist in core (now that date module was merged into core). There might be a new name for it or an equivalent.

**Comment by Al-Rozhkov** [comment]
This PR (https://github.com/backdrop/backdrop/pull/1928) fixes the problem.

**Comment by laryn** [comment]
Fixed in core: https://github.com/backdrop/backdrop/pull/3163
