### ISSUE TITLE
Restore missing "Page by date" Views pager plugin

### ISSUE THREAD

**Issue by Al-Rozhkov** [backdrop-contrib/calendar#3]
D7 Calendar module provide views templates to create new calendars with ease. Those views depends on pager plugin "Page by date" which is part of D7 Date module. In Backdrop Date module became a part of core, but "Page by date" plugin was removed.

I think we have to decide how to restore "Page by date" plugin:
* add it to Calendar itself;
* move to separate contrib module;
* restore in core Date module.

**Comment by Graham-72** [comment]
@Al-Rozhkov I don't know whether this might be of any help, but when I was working on porting Date before it was added into core, I created a repository 'Date Basic' which is still at https://github.com/backdrop-contrib/date_basic. This includes a Backdrop version of date_views_plugin_pager.inc. Is this of any use? If so, it could be added to calendar/includes perhaps.

**Comment by Al-Rozhkov** [comment]
Thank you @Graham-72! Yes, I think we can use code from date_basic.

It's not feels right to me to include date_views_plugin_pager.inc in Calendar module. Some site builders may want to use pager plugin without all other Calendar features, just plain nodes list with pager by date. We can move "Page by date" in separate contrib project and add new dependency to Calendar module.

I think we need some more feedback on it.

**Comment by Al-Rozhkov** [comment]
Hm. @Graham-72 I checked your repo of date_basic module and I didn't find date_views_plugin_pager.inc in date_views/includes. Now I start thinking that excluding date_pager form Backdrop core wasn't intentional :smile:

I'm going to open an issue in core queue to try to restore this plugin.

**Comment by Graham-72** [comment]
> I checked your repo of date_basic module and I didn't find date_views_plugin_pager.inc in date_views/includes.

@Al-Rozhkov You are right! It is not there and I wonder why I thought it was. Sorry for my mistake. I will look back at the history and see what we can retrieve.

**Comment by Al-Rozhkov** [comment]
Yay! With these pull requests Calendar module works:
- https://github.com/backdrop/backdrop/pull/1928
- https://github.com/backdrop-contrib/calendar/pull/5

I guess we near to stable release :smile:

**Comment by simone960** [comment]
Any progress so far ? Hope the module can be ported fully soon. I need to use it. Thanks everyone!

**Comment by laryn** [comment]
@Al-Rozhkov Looks like there are just some very minor review requests from @quicksketch on https://github.com/backdrop/backdrop/pull/1928

It would be great to have a functional calendar module! Thanks for all your work -- where do you need help (if any)?

**Comment by Al-Rozhkov** [comment]
I have made requested changes. Unfortunately, I can't continue my work on this, so feel free to pick it up.

BTW I have working Calendar module with 2 PR's from above on production without any problems.

**Comment by Graham-72** [comment]
@Al-Rozhkov thank you for all your work on this. I now have time to look at it again. Your pull request at backdrop/backdrop#1928 is complicated but essential. Thanks.

**Comment by olafgrabienski** [comment]
For the related [core issue](https://github.com/backdrop/backdrop-issues/issues/2766) there is a recent PR which should fix this issue: https://github.com/backdrop/backdrop/pull/3163

**Comment by laryn** [comment]
Fixed in core: https://github.com/backdrop/backdrop/pull/3163
