### ISSUE TITLE
Whats the status of this module? 

### ISSUE THREAD

**Issue by docwilmot** [backdrop-contrib/calendar#7]
It installs for me but I get `Broken/missing handler` for the `Date: Date (node)` contextual filter, which doesnt exist it seems.

**Comment by indigoxela** [comment]
I suspect, this is the third or fourth Issue reporting the same problem - missing handlers.
If the only show stopper for porting Calendar is the missing handler / plugin, then we might have some progress now.

Very likely this gets fixed with this revived core [PR](https://github.com/backdrop/backdrop/pull/3163), but I didn't verify. Is anyone willing to check that?

Other Calendar Issues, that seem related:

- https://github.com/backdrop-contrib/calendar/issues/3
- https://github.com/backdrop-contrib/calendar/issues/2
- https://github.com/backdrop-contrib/calendar/issues/1

**Comment by Graham-72** [comment]
@indigoxela the status is that at present it needs a maintainer.

**Comment by docwilmot** [comment]
@Graham-72 I've tested this module since last night's core commits and it now works (yay!). I've created 4 disabled Views of Node, User, Comment and File created dates and Backdrop-compatible config files for them. Will do a PR sometime soon so we can release a version of Calendar once 1.17.0 is live.

**Comment by Graham-72** [comment]
@docwilmot well done for getting this working. I doubt that I will now be needing to make use of the module so would prefer to leave it to others to progress to a new working release.

**Comment by laryn** [comment]
I may need this for an upcoming project so should be able to help with testing, etc. @docwilmot.

**Comment by docwilmot** [comment]
Branch and PR up. Only adds default views as module works fine otherwise with 1.17.0 core.

**Comment by docwilmot** [comment]
Todo:
- Upgrade path
- Remove any references to creating from templates, as this doesn't exist in Backdrop Views.

**Comment by laryn** [comment]
- Also should add a dependency in the `.info` file for `system (>= 1.17.0)`

**Comment by docwilmot** [comment]
OK done, but put everything in one PR to save time.
- Default Views
- Upgrade path (needs testing)
- Removed references to Views default templates
- Added dependency on core >= 1.17.0
- Removed Colorbox support. This was provided by the default templates and there is no obvious way to reproduce this without that code, sorry.

**Comment by laryn** [comment]
@docwilmot Thanks! It's on my list to test, but it might be next week.

**Comment by djzwerg** [comment]
Are there any updates?

**Comment by Wylbur** [comment]
I'll also add a comment here to see if we can restart work to get this module running.

**Comment by laryn** [comment]
@Wylbur If memory serves there's a PR that makes big progress but we're lacking a maintainer to do final testing and merge. Interested? 😸 

(The project(s) I was planning to use this on went in a different direction so I got pulled away and haven't been using it).

**Comment by alanmels** [comment]
> @Wylbur If memory serves there's a PR that makes big progress but we're lacking a maintainer to do final testing and merge. Interested? 😸
> 
> (The project(s) I was planning to use this on went in a different direction so I got pulled away and haven't been using it).

Hello. Do you mean this PR https://github.com/backdrop-contrib/calendar/tree/add-default-views? I tried it and see not difference in effect. I'd appreciate how to make this module work for content type date fields as currently only user fields work.

**Comment by argiepiano** [comment]
@alanmels, if you had installed the module and then patched it, chances are that you did not install the new views in the patch. Those views will get installed only if you completely uninstall the module, patch it, and then reinstall it (unless there is an update hook, which I doubt).
