### ISSUE TITLE
calendar row plugin array issue

### ISSUE THREAD

**Issue by pgrayove-mcpl** [backdrop-contrib/calendar#9]
Getting this error for a calendar view. The notice repeats multiple times. `Notice: Trying to access array offset on value of type null in calendar_plugin_row->render() (line 438 of /app/modules/contrib/calendar/includes/calendar_plugin_row.inc).`

This is line 438: `$increment = $instance['widget']['settings']['increment'];`

Additionally, the Month and Year or Week doesn't display at the top of the calendar display.

This is a view ported from D7.  The Backdrop site is running PHP 7.4.

**Comment by pgrayove-mcpl** [comment]
Found this [issue documented on Drupal](https://www.drupal.org/project/calendar/issues/3134081). I implemented the fix in the patch and it seems to fix this issue. Will do a PR to fix.

**Comment by herbdool** [comment]
I've merged this on behalf of the @backdrop-contrib/bug-squad. Since this was already merged into the D7 project, it should be fine here. I also tested it.
